name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python train.py

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: sentiment-model
          path: models/sentiment_model

  test:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: sentiment-model
          path: models/sentiment_model

      - name: Run tests
        run: pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: sentiment-model
          path: models/sentiment_model

      - name: Build and simulate deploy to Hugging Face
        run: python -m deploy.deploy

      - name: Upload deploy package
        uses: actions/upload-artifact@v4
        with:
          name: huggingface-space-package
          path: dist/huggingface_space

  monitor:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: sentiment-model
          path: models/sentiment_model

      - name: Build reference/current datasets
        run: python -m monitoring.build_dataset

      - name: Generate monitoring report
        run: python -m monitoring.report

      - name: Upload monitoring report
        uses: actions/upload-artifact@v4
        with:
          name: monitoring-report
          path: monitoring/reports
